# Конфигурация Telegram бота
telegram:
  bot:
    username: ${TELEGRAM_BOT_USERNAME:YourBotUsername}
    token: ${TELEGRAM_BOT_TOKEN:YourBotToken}

# Конфигурация кампаний и государственных органов
campaigns:
  - id: campaign1
    name: "Кампания по декларации налогов"
    agencies:
      - id: agency1
        name: "Федеральная налоговая служба"
        template-file: "templates/fns/template.txt"
        instruction-file: "templates/fns/instruction.txt"
        delivery-options:
          - "file"
          - "text"
      - id: agency2
        name: "Местная налоговая инспекция"
        template-file: "templates/local-tax/template.txt"
        instruction-file: "templates/local-tax/instruction.txt"
        delivery-options:
          - "file"
          - "text"
  - id: campaign2
    name: "Кампания по социальным льготам"
    agencies:
      - id: agency3
        name: "Департамент социальной защиты"
        template-file: "templates/social/template.txt"
        instruction-file: "templates/social/instruction.txt"
        delivery-options:
          - "file"
          - "text"
      - id: agency4
        name: "Информационный центр"
        instruction-file: "templates/social/instruction.txt"
        delivery-options: []
      - id: agency5
        name: "Принять участие в публичном обсуждении"
        instruction-file: "templates/social/instruction.txt"
        delivery-options: []

# Конфигурация статистики
statistics:
  file-path: "data/statistics.json"

# Конфигурация логирования
logging:
  config: classpath:logback.xml